//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisterBotService {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResource() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SisterBotService.SqlResource", typeof(SqlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DECLARE @ERRORI INT = (SELECT COUNT(*)
        ///FROM dbo.DATI_RICHIESTE
        ///WHERE ID_RICHIESTA = @ID_RICHIESTA AND 
        /// STATO = 3 AND
        /// VERIFICATO = 1) 
        ///IF @ERRORI&gt;0 
        /// SELECT 1
        ///ELSE
        /// SELECT 0.
        /// </summary>
        internal static string getErroriInRicerca {
            get {
                return ResourceManager.GetString("getErroriInRicerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SELECT DISTINCT TOP (1) RIC.ID_RICHIESTA, RIC.DATA
        ///FROM dbo.RICHIESTE RIC
        ///INNER JOIN dbo.DATI_RICHIESTE DR ON DR.ID_RICHIESTA = RIC.ID_RICHIESTA
        ///WHERE RIC.STATO IN (0,3) AND RIC.NTENTATIVO &lt; 3 AND DR.STATO IN (0,3) AND RIC.ID_SERVIZIO IN (0,1,2,3,4)
        ///ORDER BY RIC.DATA.
        /// </summary>
        internal static string getPrimaRicercaDaFare {
            get {
                return ResourceManager.GetString("getPrimaRicercaDaFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DECLARE @FATTI INT = (SELECT COUNT(*)
        ///FROM dbo.DATI_RICHIESTE
        ///WHERE ID_RICHIESTA = @ID_RICHIESTA AND 
        /// STATO = 2 AND
        /// VERIFICATO = 1) 
        ///
        ///DECLARE @DA_FARE INT = (SELECT COUNT(*)
        ///FROM dbo.DATI_RICHIESTE
        ///WHERE ID_RICHIESTA = @ID_RICHIESTA AND 
        /// STATO &lt;&gt; 2 AND
        /// VERIFICATO = 1)
        ///IF @DA_FARE&gt;0 AND @FATTI &gt;0
        /// SELECT 1
        ///ELSE
        /// SELECT 0.
        /// </summary>
        internal static string getRicercaIncompleta {
            get {
                return ResourceManager.GetString("getRicercaIncompleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SELECT 1
        ///FROM dbo.RICHIESTE
        ///WHERE STATO = 1 AND ID_SERVIZIO IN (0,1,2,3,4).
        /// </summary>
        internal static string getRicercheInCorso {
            get {
                return ResourceManager.GetString("getRicercheInCorso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SELECT COUNT(*)
        ///FROM RICHIESTE r
        ///JOIN DATI_RICHIESTE dr on r.ID_RICHIESTA = dr.ID_RICHIESTA
        ///WHERE r.ID_SERVIZIO = 1 
        ///AND
        /// EMAIL = &apos;ISPCATASisterBot.Ciro@azinfocollection.it&apos;
        ///AND 
        /// r.STATO IN (0,1,3)
        ///AND
        /// dr.ALTRO2 IS NOT NULL
        ///AND 
        /// DATEADD(hh,5,[data]) &lt; getdate().
        /// </summary>
        internal static string getRichiestePendingMoreThanFiveHours {
            get {
                return ResourceManager.GetString("getRichiestePendingMoreThanFiveHours", resourceCulture);
            }
        }
    }
}
